### PR TITLE
Discover Features Protocol 2.0

### PR DESCRIPTION
**Pull request by rodolfomiranda**
Add missing Discover Features Protocol from spec

### CODE REVIEW

**Comment by TimoGlastra** [comment]
The aries RFCs also define the discover features protocol 2.0. Are these fully compliant with each other? Or should the didcomm one have been version 3.0?

**Comment by rodolfomiranda** [comment]
> The aries RFCs also define the discover features protocol 2.0. Are these fully compliant with each other? Or should the didcomm one have been version 3.0?

I missed it. I'll move that reference to 3.0 and add 1.0 and 2.0 from Aries

**Comment by TelegramSam** [comment]
So: This is a larger issue. I believe the semantics of the protocol are the same between the v2 defined in Aries, and v2 defined in the DIDComm spec. So, do we need a new version?

(The example with v2 specified is in error either way)

**Comment by rodolfomiranda** [comment]
Added reference to Aries and provide examples for both DIDComm v1 and v2

**Pull request merged**
